### PR TITLE
docker-compose.yml for profile-manager added +composer container

### PR DESCRIPTION
**Pull request by ebm17915**
**Description**
Added docker-compose.yml file to profile-manager repo
**Testing**
1. Make sure docker-compose.yml is inside profile-manager directory
2. Make sure you have .env
3. Run the following command build and open the container: 
docker-compose up -d
4. Check localhost:8080 to visit the project
5. Run the following command to close the container:
docker-compose down

### CODE REVIEW

**Review by digitalsoba — APPROVED** [review]
Looks good, verified/tested from demo.

**Review by luisjg — APPROVED** [review]
👍

**Review by luisjg — CHANGES_REQUESTED** [review]
Based on the discussion with @ruizjorgealt we'd want composer on this container as well.

**Review by luisjg — APPROVED** [review]
👍

**Pull request merged**
